### ISSUE TITLE
(Suggestion) Put the arrows inside the padding

### ISSUE THREAD

**Issue by Daviid-P** [tofsjonas/sortable#42]
If you `text-align` to the right you have something like this.

![image](https://user-images.githubusercontent.com/7734808/226653816-82ff33ba-5c3b-4968-9dfd-ba0f9cbba795.png)

In the header there's a space for the arrows.

If we do this:

```css
th {
  position: relative;
}
th::after {
  position: absolute;
}
```

we can put the arrows inside the padding and the text always aligns in th and td (assuming same `text-align`)
